PROFILE_NAMES = DEVICE_firefly_roc-rk3328-cc DEVICE_friendlyarm_nanopi-r2c DEVICE_friendlyarm_nanopi-r2s DEVICE_friendlyarm_nanopi-r4s DEVICE_pine64_rockpro64 DEVICE_radxa_rock-pi-4a DEVICE_xunlong_orangepi-r1-plus DEVICE_xunlong_orangepi-r1-plus-lts
DEVICE_firefly_roc-rk3328-cc_NAME:=Firefly ROC-RK3328-CC
DEVICE_firefly_roc-rk3328-cc_HAS_IMAGE_METADATA:=1
DEVICE_firefly_roc-rk3328-cc_SUPPORTED_DEVICES:=firefly,roc-rk3328-cc
DEVICE_firefly_roc-rk3328-cc_PACKAGES:=
DEVICE_friendlyarm_nanopi-r2c_NAME:=FriendlyARM NanoPi R2C
DEVICE_friendlyarm_nanopi-r2c_HAS_IMAGE_METADATA:=1
DEVICE_friendlyarm_nanopi-r2c_SUPPORTED_DEVICES:=friendlyarm,nanopi-r2c
DEVICE_friendlyarm_nanopi-r2c_PACKAGES:=kmod-usb-net-rtl8152
DEVICE_friendlyarm_nanopi-r2s_NAME:=FriendlyARM NanoPi R2S
DEVICE_friendlyarm_nanopi-r2s_HAS_IMAGE_METADATA:=1
DEVICE_friendlyarm_nanopi-r2s_SUPPORTED_DEVICES:=friendlyarm,nanopi-r2s
DEVICE_friendlyarm_nanopi-r2s_PACKAGES:=kmod-usb-net-rtl8152
DEVICE_friendlyarm_nanopi-r4s_NAME:=FriendlyARM NanoPi R4S 4GB LPDDR4
DEVICE_friendlyarm_nanopi-r4s_HAS_IMAGE_METADATA:=1
DEVICE_friendlyarm_nanopi-r4s_SUPPORTED_DEVICES:=friendlyarm,nanopi-r4s
DEVICE_friendlyarm_nanopi-r4s_PACKAGES:=kmod-r8169
DEVICE_pine64_rockpro64_NAME:=Pine64 RockPro64
DEVICE_pine64_rockpro64_HAS_IMAGE_METADATA:=1
DEVICE_pine64_rockpro64_SUPPORTED_DEVICES:=pine64,rockpro64
DEVICE_pine64_rockpro64_PACKAGES:=
DEVICE_radxa_rock-pi-4a_NAME:=Radxa ROCK Pi 4A
DEVICE_radxa_rock-pi-4a_HAS_IMAGE_METADATA:=1
DEVICE_radxa_rock-pi-4a_SUPPORTED_DEVICES:=radxa,rockpi4a radxa,rockpi4
DEVICE_radxa_rock-pi-4a_PACKAGES:=
DEVICE_xunlong_orangepi-r1-plus_NAME:=Xunlong Orange Pi R1 Plus
DEVICE_xunlong_orangepi-r1-plus_HAS_IMAGE_METADATA:=1
DEVICE_xunlong_orangepi-r1-plus_SUPPORTED_DEVICES:=xunlong,orangepi-r1-plus
DEVICE_xunlong_orangepi-r1-plus_PACKAGES:=kmod-usb-net-rtl8152
DEVICE_xunlong_orangepi-r1-plus-lts_NAME:=Xunlong Orange Pi R1 Plus LTS
DEVICE_xunlong_orangepi-r1-plus-lts_HAS_IMAGE_METADATA:=1
DEVICE_xunlong_orangepi-r1-plus-lts_SUPPORTED_DEVICES:=xunlong,orangepi-r1-plus-lts
DEVICE_xunlong_orangepi-r1-plus-lts_PACKAGES:=kmod-usb-net-rtl8152
